// ────────────────────────────────────────────
// EduDownloader — Cookie Updater
// 1-Click Sync to Render
// ────────────────────────────────────────────

// ⚠️ ¡Pega tu API Key de Render aquí! ⚠️
// Obtenla en: https://dashboard.render.com/account/api-keys
const RENDER_API_KEY = 'rnd_f6hjKgeHOqJ4RYdBbCgh6Pp3rebU';

const RENDER_SERVICE_ID = 'srv-da71lavavr4c7386nus0';

// YouTube cookie names that cobalt needs
const YT_COOKIE_NAMES = [
  '__Secure-3PSID', '__Secure-3PAPISID', '__Secure-1PSID', '__Secure-1PAPISID',
  'SAPISID', 'APISID', 'HSID', 'SSID', 'SID', 'GPS', 'YSC',
  'VISITOR_INFO1_LIVE', '__Secure-3PSIDCC', '__Secure-3PSIDTS',
  '__Secure-1PSIDCC', '__Secure-1PSIDTS',
];

async function getAllYouTubeCookies() {
  const domains = ['https://www.youtube.com', 'https://youtube.com'];
  const allCookies = [];
  const seen = new Set();
  for (const url of domains) {
    const cookies = await chrome.cookies.getAll({ url });
    for (const c of cookies) {
      if (!seen.has(c.name)) {
        seen.add(c.name);
        allCookies.push(c);
      }
    }
  }
  return allCookies;
}

function toNetscapeFormat(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by EduDownloader Cookie Updater', ''];
  for (const c of cookies) {
    const domain = c.domain || '.youtube.com';
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry = c.expirationDate ? Math.round(c.expirationDate) : 2147483647;
    const name = c.name;
    const value = c.value;
    lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${name}\t${value}`);
  }
  return lines.join('\n');
}

function showStatus(type, message) {
  const box = document.getElementById('statusBox');
  const text = document.getElementById('statusText');
  const spinner = document.getElementById('statusSpinner');
  box.className = `status-box ${type}`;
  box.style.display = 'flex';
  text.textContent = message;
  spinner.style.display = type === 'loading' ? 'block' : 'none';
}

async function uploadCookies() {
  const btn = document.getElementById('uploadBtn');

  if (RENDER_API_KEY === 'AQUI_VA_TU_API_KEY') {
    showStatus('error', '⚠️ Fálta configurar la API Key en popup.js');
    return;
  }

  showStatus('loading', 'Leyendo cookies...');
  btn.disabled = true;

  try {
    const cookies = await getAllYouTubeCookies();
    if (cookies.length === 0) {
      showStatus('error', 'No hay cookies. ¿Estás logueado en YouTube?');
      btn.disabled = false; return;
    }

    const netscapeContent = toNetscapeFormat(cookies);
    showStatus('loading', `Subiendo ${cookies.length} cookies...`);

    // 1. Get current env vars
    const getRes = await fetch(`https://api.render.com/v1/services/${RENDER_SERVICE_ID}/env-vars`, {
      method: 'GET',
      headers: { 'Authorization': `Bearer ${RENDER_API_KEY}`, 'Accept': 'application/json' },
    });
    if (!getRes.ok) throw new Error(`Error GET: ${getRes.status}`);
    
    // 2. Build updated vars
    const filtered = (await getRes.json())
      .filter(v => !['YOUTUBE_COOKIES', 'YOUTUBE_SESSION_GENERATOR'].includes(v.envVar.key))
      .map(v => ({ key: v.envVar.key, value: v.envVar.value }));
    filtered.push({ key: 'YOUTUBE_COOKIES', value: netscapeContent });

    // 3. Put vars
    showStatus('loading', 'Actualizando Render...');
    const putRes = await fetch(`https://api.render.com/v1/services/${RENDER_SERVICE_ID}/env-vars`, {
      method: 'PUT',
      headers: { 'Authorization': `Bearer ${RENDER_API_KEY}`, 'Content-Type': 'application/json', 'Accept': 'application/json' },
      body: JSON.stringify(filtered),
    });
    if (!putRes.ok) throw new Error(`Error PUT: ${putRes.status}`);

    // 4. Redeploy
    showStatus('loading', 'Reiniciando servidor...');
    await fetch(`https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${RENDER_API_KEY}`, 'Content-Type': 'application/json', 'Accept': 'application/json' },
      body: JSON.stringify({ clearCache: false }),
    });

    showStatus('success', '¡Listo! YouTube disponible en 2 mins.');
  } catch (e) {
    showStatus('error', e.message);
  } finally {
    btn.disabled = false;
  }
}

document.addEventListener('DOMContentLoaded', () => {
  document.getElementById('uploadBtn').addEventListener('click', uploadCookies);
});
